/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import java.awt.BorderLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import openh2o.GlobalVars;
import org.netbeans.api.visual.graph.GraphScene;

/**
 *
 * @author cfviper
 * Reference: http://netbeans.org/kb/trails/platform.html
 */
public class TimeLineEditor extends javax.swing.JPanel {

    private static JPanel jpTimeLine = new JPanel();
    private static JScrollPane scrollPane;
    //static ConnectSceneDelete classCS;
    
    public TimeLineEditor() {
     //   initComponents();
        
        // Might be able to delete this class
    }
    
    static public JScrollPane getTimeLineEditor(GraphScene scene) {
       // scrollPane = new JScrollPane();
//        jpTimeLine.setLayout(new BorderLayout());
//        jpTimeLine.add(new JLabel("foo bar"));
//        scrollPane.add(jpTimeLine);
//        
//        //Add it to the JScrollPane:
//        scrollPane.setViewportView(scene.createView());
//
//        //Add the SatellitView to the scene:
//        // Sat View doesn't display
//        jpTimeLine.add(scene.createSatelliteView(), BorderLayout.WEST);
        return scrollPane;
    }
    static public void refreshTimeLinePanel(){
        jpTimeLine.repaint();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
